openapi: 3.1.0
info:
  title: Sample to demo remove-x-internal
  version: 1.0.0
  description: |
    This API showcases usage of the `x-internal` property and a single OpenAPI file to generate separate internal and external OAS definitions.
servers:
  - url: https://ebcdea8b-433b-4fc1-83d3-vib.remockly.com
    description: Vib server
paths:
  /stars:
    get:
      x-internal: true
      operationId: getStars
      summary: Get list of stars 2
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/star"
    post:
      x-internal: true
      operationId: postStars
      summary: Register a star 2
      description: Blah Blah
      requestBody:
        content: 
          application/json:
            schema:
              $ref: "#/components/schemas/star"
  /suns:
    get:
      x-internal: true
      operationId: getSuns
      summary: Get list of suns
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/star"
    
components:
  schemas:
    star:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        brightness:
          type: object
          properties:
            luminosity:
              type: number
            magnitude:
              type: number
        size:
          type: number
        mass:
          type: number
        hasVib:
          type: boolean
